redis:
  host: localhost
  port: 6379
  password: ""
  cluster: "SmoothSync"
mongo:
  uri: "mongodb://localhost:27017"
  database: "SmoothSync"

synchronization:
  join-delay: 500 # Delay in milliseconds before a player is synchronized after joining the server