redis:
  host: localhost
  port: 6379
  password: ""
  cluster: "SmoothSync"
mongo:
  uri: "mongodb://localhost:27017"
  database: "SmoothSync"

synchronization:
  timeouts: # Timeouts in milliseconds
    join: 2000
    updated-user-request: 2000
  join-delay: 500 # Delay in milliseconds before a player is synchronized after joining the server
  prevent-damage: true # Prevent damage to the player while synchronizing
  features:
    inventory: true
    ender-chest: true
    game-mode: true
    experience: true
    potion-effects: true
    health: true
    food: true
    air: true
    location: false
    advancements: true
    statistics: true

data-update:
  # When Performance Mode is enabled (performance-mode: true):
  # - Regular Interval Update: REDIS
  # - Update on Quit: REDIS & MONGODB
  # - Update on Death: REDIS
  # - Update on Server Stop: REDIS & MONGODB
  #
  # When Performance Mode is disabled (performance-mode: false):
  # - Regular Interval Update: REDIS & MONGODB
  # - Update on Quit: REDIS & MONGODB
  # - Update on Death: REDIS & MONGODB
  # - Update on Server Stop: REDIS & MONGODB
  performance-mode: true
  save-interval: 300 # Interval in seconds between regular updates
  update-on-death: true

invsee:
  enabled: true
  menu:
    title: "&8%player%'s inventory"
endersee:
  enabled: true
  menu:
    title: "&8%player%'s enderchest"
